---
title: "ErBr_report"
author: "Michelle DePrenger-Levin"
date: "October 31, 2016"
output: html_document
---

###Packages
```{r}
library(prism)
library(ggplot2)
library(raster)
library(plotrix)
library(devtools)
library(RCurl)
library(scales)
```

Clean slate
```{r}
rm(list=ls(all=TRUE))

```

Functions   
```{r}
# StagePVA_Function.R
script <- getURL("https://raw.githubusercontent.com/DenverBotanicGardens/ErBr/master/CountPVA.R",
                 ssl.verifypeer = FALSE)
eval(parse(text = script))

```

###Data    
Download Raw Data and and Summary Table
<https://research.botanicgardens.org/admin/>
```{r}
currentyr <- as.numeric(format(as.Date(Sys.Date(),format="%Y-%m-%d"), "%Y"))
rawdatapath <- paste("Q:/Research/All_Projects_by_Species/Eriogonum SPECIES/Eriogonum_brandegeei/", 
                     currentyr,"_ErBr/rawdata_",
                     currentyr, ".csv", collapse = '', sep = '')

erbr.raw <- read.csv(path.expand(rawdatapath), na.strings = "na")

summarypath <- paste("Q:/Research/All_Projects_by_Species/Eriogonum SPECIES/Eriogonum_brandegeei/", 
                     currentyr,"_ErBr/summarytable_",
                     currentyr, ".csv", collapse = '', sep = '')
erbr.summary <- read.csv(path.expand(summarypath), na.strings = "na")

erbr.cleora <- erbr.summary[erbr.summary$Site == "Cleora" & erbr.summary$Year == 2004,]
erbr.summary <- erbr.summary[erbr.summary$Site != "Cleora",]
erbr.summary$Site <- factor(erbr.summary$Site)
```

# Climate Data
just use the data downloaded for AsMi
```{r}
options(prism.path = "Q:/Research/All_Projects_by_Species/Astragalus SPECIES/Astragalus_microcymbus/PRISM_asmiclimate")

erbrlatlong <- data.frame(Lat = 38.5434, Long = -105.2184)

maxs <- grep("tmax", ls_prism_data(absPath=TRUE)[,2])
mins <- grep("tmin", ls_prism_data(absPath = TRUE)[,2])
ppt <- grep("ppt", ls_prism_data(absPath = TRUE)[,2])

avgTemps.max <- lapply(maxs, function(x){
  rastertemps <- raster(ls_prism_data(absPath=TRUE)[x,2])
  data.frame(data = extract(rastertemps, erbrlatlong[,c("Long","Lat")]), date = ls_prism_data()[x,])
})

avgTemps.min <- lapply(mins, function(x){
  rastertemps <- raster(ls_prism_data(absPath=TRUE)[x,2])
  data.frame(data = extract(rastertemps, erbrlatlong[,c("Long","Lat")]), date = ls_prism_data()[x,])
})

avgPrecip <- lapply(ppt, function(x){
  rastertemps <- raster(ls_prism_data(absPath=TRUE)[x,2])
  data.frame(data = extract(rastertemps, erbrlatlong[,c("Long","Lat")]), date = ls_prism_data()[x,])
})

mins.avg <- do.call(rbind, avgTemps.min)
maxs.avg <- do.call(rbind, avgTemps.max)
ppt.avg <- do.call(rbind, avgPrecip)

erbr.climate <- cbind(mins.avg,maxs.avg[,1],ppt.avg[,1])
names(erbr.climate) <- c("tmin","date","tmax","ppt")

#Pull out month and year
#date is a factor
erbr.climate$date <- as.character(erbr.climate$date)

#split by _ select the YYYYMM numbers
erbr.climate$Year <- as.numeric(substr(vapply(strsplit(erbr.climate$date, '_'), 
                                   function(x) x[5], character(1)), 1,4))
erbr.climate$Month <- as.numeric(substr(vapply(strsplit(erbr.climate$date, '_'), 
                                   function(x) x[5], character(1)), 5,6))

erbr.c <- erbr.climate[,-2]
erbr.c$Prev12 <- erbr.c$Year
erbr.c$Prev12[erbr.c$Month > 7] <- erbr.c$Year[erbr.c$Month > 7]+1
```

Demography    

Figure 2
```{r}
ggplot(erbr.summary, aes(Year, SumOfRosettes,colour = Site, shape = Site))+
  stat_summary(fun.y = mean, position=position_dodge(width=0.5),
               fun.ymin = function(x) mean(x) - std.error(x),
               fun.ymax = function(x) mean(x) + std.error(x),
               geom = "errorbar")+
   stat_summary(fun.y = mean, position=position_dodge(width=0.5),
               fun.ymin = function(x) mean(x) - std.error(x),
               fun.ymax = function(x) mean(x) + std.error(x),
               geom = "point")+
  stat_summary(fun.y = mean,
               geom = "line")+
  theme_bw() +
  ylab("Average rosettes per transect")+
  scale_color_manual(values=c("#000000","#7e7e7e"),
                     labels = c("Garden Park East","Garden Park West"))+
  scale_shape_manual(values=c(1,2),
                     labels = c("Garden Park East","Garden Park West"))+
  theme(legend.justification=c(1,1), legend.position=c(1,1)) 
  

```

Count PVA
```{r}
gpe.summary <- aggregate(SumOfRosettes ~ Year,
                         data = erbr.summary[erbr.summary$Site == "Garden Park East",], mean)
gpw.summary <- aggregate(SumOfRosettes ~ Year,
                         data = erbr.summary[erbr.summary$Site == "Garden Park West",], mean)

GPE <- CountPVA(gpe.summary, "Year","SumOfRosettes")
GPW <- CountPVA(gpw.summary, "Year","SumOfRosettes")

sapply(GPE[,1:3], function(x) exp(x))
sapply(GPW[,1:3], function(x) exp(x))
```

Figure 3a
```{r}
ggplot(erbr.summary, aes(Year, SumOfInfl,colour = Site, shape = Site))+
  stat_summary(fun.y = mean, position=position_dodge(width=0.5),
               fun.ymin = function(x) mean(x) - std.error(x),
               fun.ymax = function(x) mean(x) + std.error(x),
               geom = "errorbar")+
   stat_summary(fun.y = mean, position=position_dodge(width=0.5),
               fun.ymin = function(x) mean(x) - std.error(x),
               fun.ymax = function(x) mean(x) + std.error(x),
               geom = "point")+
  stat_summary(fun.y = mean, position=position_dodge(width=0.5),
               geom = "line")+
  theme_bw() +
  ggtitle("a)") +
  theme(plot.title=element_text(hjust=0))+
  ylab("Average inflorescences per transect")+
  scale_color_manual(values=c("#000000","#7e7e7e"),
                     labels = c("Garden Park East","Garden Park West"))+
  scale_shape_manual(values=c(1,2),
                     labels = c("Garden Park East","Garden Park West"))+
  theme(legend.justification=c(1,1), legend.position=c(1,1)) 


```

Figure 3b
```{r}
# inflorescences per rosette
erbr.summary$InflperRos <- erbr.summary$SumOfInfl/erbr.summary$SumOfRosettes
erbr.summary$InflperRos[is.na(erbr.summary$InflperRos)] <- 0

ggplot(erbr.summary, aes(Year, InflperRos,colour = Site, shape = Site))+
  stat_summary(fun.y = mean, position=position_dodge(width=0.5),
               fun.ymin = function(x) mean(x) - std.error(x),
               fun.ymax = function(x) mean(x) + std.error(x),
               geom = "errorbar")+
   stat_summary(fun.y = mean, position=position_dodge(width=0.5),
               fun.ymin = function(x) mean(x) - std.error(x),
               fun.ymax = function(x) mean(x) + std.error(x),
               geom = "point")+
  stat_summary(fun.y = mean, position=position_dodge(width=0.5),
               geom = "line")+
  theme_bw() +
  ggtitle("b)") +
  theme(plot.title=element_text(hjust=0))+
  ylab("Average inflorescences per rosettes")+
  scale_color_manual(values=c("#000000","#7e7e7e"),
                     labels = c("Garden Park East","Garden Park West"))+
  scale_shape_manual(values=c(1,2),
                     labels = c("Garden Park East","Garden Park West"))+
  theme(legend.justification=c(1,1), legend.position=c(1,1)) 

```

Averages before and after 2011
```{r}
erbr.summary$drought <- "before"
erbr.summary$drought[erbr.summary$Year > 2010] <- "after"
erbr.summary$drought <- factor(erbr.summary$drought, levels = c("before","after"))

agg.erbr <- aggregate(SumOfRosettes ~ Site + drought, data=erbr.summary, mean)
agg.erbr$SE <- aggregate(SumOfRosettes ~ Site + drought, data=erbr.summary, std.error)[,3]
```

```{r}
ggplot(agg.erbr, aes(drought,SumOfRosettes, colour = Site))+
  geom_point()+
  geom_errorbar(aes(ymax=SumOfRosettes + SE, ymin=SumOfRosettes - SE), width=0.1)+
  theme_bw()+
  xlab("Drought conditions (2011-2013)")+
  ylab("Average rosettes")+
  theme(legend.justification=c(1,1), legend.position=c(1,1))

```

Figure 4a
```{r}
ggplot(erbr.summary, aes( Year,SumOfArea,colour = Site, shape = Site))+
  stat_summary(fun.y = mean, position=position_dodge(width=0.5),
               fun.ymin = function(x) mean(x) - std.error(x),
               fun.ymax = function(x) mean(x) + std.error(x),
               geom = "errorbar")+
   stat_summary(fun.y = mean, position=position_dodge(width=0.5),
               fun.ymin = function(x) mean(x) - std.error(x),
               fun.ymax = function(x) mean(x) + std.error(x),
               geom = "point")+
  stat_summary(fun.y = mean, position=position_dodge(width=0.5),
               geom = "line")+
  theme_bw() +
  ggtitle("a)") +
  theme(plot.title=element_text(hjust=0))+
  ylab(expression("Average basal area (cm"^2~") per transect"))+
  scale_color_manual(values=c("#000000","#7e7e7e"),
                     labels = c("Garden Park East","Garden Park West"))+
  scale_shape_manual(values=c(1,2),
                     labels = c("Garden Park East","Garden Park West"))+
  theme(legend.justification=c(1,1), legend.position=c(1,1)) 
```

Figure 4b
```{r}
erbr.summary$RosperArea <- erbr.summary$SumOfRosettes/erbr.summary$SumOfArea

ggplot(erbr.summary, aes(Year,RosperArea,colour = Site, shape = Site))+
  stat_summary(fun.y = mean, position=position_dodge(width=0.5),
               fun.ymin = function(x) mean(x) - std.error(x),
               fun.ymax = function(x) mean(x) + std.error(x),
               geom = "errorbar")+
   stat_summary(fun.y = mean, position=position_dodge(width=0.5),
               fun.ymin = function(x) mean(x) - std.error(x),
               fun.ymax = function(x) mean(x) + std.error(x),
               geom = "point")+
  stat_summary(fun.y = mean, position=position_dodge(width=0.5),
               geom = "line")+
  theme_bw() +
  ggtitle("b)") +
  theme(plot.title=element_text(hjust=0))+
  ylab(expression("Average rosettes per basal area (cm"^2~")"))+
  scale_color_manual(values=c("#000000","#7e7e7e"),
                     labels = c("Garden Park East","Garden Park West"))+
  scale_shape_manual(values=c(1,2),
                     labels = c("Garden Park East","Garden Park West"))+
  theme(legend.justification=c(1,1), legend.position=c(1,1)) 

```

Figure 4c
```{r}
erbr.summary$InflperArea <- erbr.summary$SumOfInfl/erbr.summary$SumOfArea

ggplot(erbr.summary, aes(Year,InflperArea,colour = Site, shape = Site))+
  stat_summary(fun.y = mean, position=position_dodge(width=0.5),
               fun.ymin = function(x) mean(x) - std.error(x),
               fun.ymax = function(x) mean(x) + std.error(x),
               geom = "errorbar")+
   stat_summary(fun.y = mean, position=position_dodge(width=0.5),
               fun.ymin = function(x) mean(x) - std.error(x),
               fun.ymax = function(x) mean(x) + std.error(x),
               geom = "point")+
  stat_summary(fun.y = mean, position=position_dodge(width=0.5),
               geom = "line")+
  theme_bw() +
  ggtitle("c)") +
  theme(plot.title=element_text(hjust=0))+
  ylab(expression("Average inflorescences per basal area (cm"^2~")"))+
  scale_color_manual(values=c("#000000","#7e7e7e"),
                     labels = c("Garden Park East","Garden Park West"))+
  scale_shape_manual(values=c(1,2),
                     labels = c("Garden Park East","Garden Park West"))+
  theme(legend.justification=c(1,1), legend.position=c(1,1)) 

```

Figure 5a
```{r}
ggplot(erbr.summary, aes(Year,SumOfBrowsedInfl,colour = Site, shape = Site))+
  stat_summary(fun.y = mean, position=position_dodge(width=0.25),
               fun.ymin = function(x) mean(x) - std.error(x),
               fun.ymax = function(x) mean(x) + std.error(x),
               geom = "errorbar")+
   stat_summary(fun.y = mean, position=position_dodge(width=0.25),
               fun.ymin = function(x) mean(x) - std.error(x),
               fun.ymax = function(x) mean(x) + std.error(x),
               geom = "point")+
  stat_summary(fun.y = mean, position=position_dodge(width=0.25),
               geom = "line")+
  theme_bw() +
  ggtitle("a)") +
  theme(plot.title=element_text(hjust=0))+
  ylab("Average browsed inflorescences per transect")+
  scale_color_manual(values=c("#000000","#7e7e7e"),
                     labels = c("Garden Park East","Garden Park West"))+
  scale_shape_manual(values=c(1,2),
                     labels = c("Garden Park East","Garden Park West"))+
  theme(legend.justification=c(1,1), legend.position=c(1,1)) 

```

Figure 5b
```{r}
erbr.summary$InflBrperInfl <- erbr.summary$SumOfBrowsedInfl/erbr.summary$SumOfInfl

ggplot(erbr.summary, aes(Year,InflBrperInfl,colour = Site, shape = Site))+
  stat_summary(fun.y = mean, position=position_dodge(width=0.25),
               fun.ymin = function(x) mean(x) - std.error(x),
               fun.ymax = function(x) mean(x) + std.error(x),
               geom = "errorbar")+
   stat_summary(fun.y = mean, position=position_dodge(width=0.25),
               fun.ymin = function(x) mean(x) - std.error(x),
               fun.ymax = function(x) mean(x) + std.error(x),
               geom = "point")+
  stat_summary(fun.y = mean, position=position_dodge(width=0.25),
               geom = "line")+
  theme_bw() +
  ggtitle("b)") +
  theme(plot.title=element_text(hjust=0))+
  ylab("Percent browsed inflorescences")+
  scale_color_manual(values=c("#000000","#7e7e7e"),
                     labels = c("Garden Park East","Garden Park West"))+
  scale_shape_manual(values=c(1,2),
                     labels = c("Garden Park East","Garden Park West"))+
  theme(legend.justification=c(1,1), legend.position=c(1,1)) +
  scale_y_continuous(labels = percent)

```

Climate
Garden Park
```{r}
#cutoff <- 0.65
cutoff <- 0.75

#### START HERE#### not by season, go by month maybe!?
cor.table<-cor(erbr.c[,c(1:3)])
data <- as.data.frame(as.table(cor.table))
combins <- combn(colnames(cor.table),2,FUN=function(x) paste(x,collapse="_"))
cor.data <- data[data$Var1 != data$Var2, ]
data <- cor.data[paste(cor.data$Var1, cor.data$Var2, sep="_") %in% combins,]
exclude <- paste(data$Var2[abs(data$Freq)>cutoff],sep=",")

#Which are correlated? 
data[abs(data$Freq)>cutoff,]

tomatch <- c("Creek","Prev12",exclude)

forpca <- season[,c(grep(paste(tomatch, collapse="|"),
                            names(season), value=TRUE, invert=TRUE))]
names(forpca)

```

